package uk.co.aegisphere.model;

import lombok.Data;

@Data
public class Count {
    /** Emperors */
    private int alienEmperorFounders;
    private int alienEmperorPremium;
    private int alienEmperorBase;
    private int humanEmperorFounders;
    private int humanEmperorPremium;
    private int humanEmperorBase;
    /** HUMANS */
    private int figyuFounders;
    private int figyuPremium;
    private int figyuBase;
    private int talosFounders;
    private int talosPremium;
    private int talosBase;
    private int melcroseFounders;
    private int melcrosePremium;
    private int melcroseBase;
    private int stemimaFounders;
    private int stemimaPremium;
    private int stemimaBase;
    private int leviathanFounders;
    private int leviathanPremium;
    private int leviathanBase;
    /** ALIENS */
    private int dagonFounders;
    private int dagonPremium;
    private int dagonBase;
    private int apollyonFounders;
    private int apollyonPremium;
    private int apollyonBase;
    private int chemoshFounders;
    private int chemoshPremium;
    private int chemoshBase;
    private int sartosisFounders;
    private int sartosisPremium;
    private int sartosisBase;
    private int archonFounders;
    private int archonPremium;
    private int archonBase;
    /** TROOPS */
    private int wagmiTroopsBase;
    private int wagmiTroopsPremium;
    private int wagmiTroopsFounders;
    private int enoguardsBase;
    private int enoguardsPremium;
    private int enoguardsFounders;
    private int scrappersBase;
    private int scrapperPremium;
    private int scrappersFounders;
    private int manicritesBase;
    private int manicritesPremium;
    private int manicritesFounders;
    private int saraguardsBase;
    private int saraguardsPremium;
    private int saraguardsFounders;
    private int immortalsBase;
    private int immortalsPremium;
    private int immortalsFounders;
    private int sayeretBase;
    private int sayeretPremium;
    private int sayeretFounders;
    private int gammadonsBase;
    private int gammadonsPremium;
    private int gammadonsFounders;
    /** AIR UNITS */
    private int obixFighterBase;
    private int obixFighterPremium;
    private int obixFighterFounders;
    private int obixBomberBase;
    private int obixBomberPremium;
    private int obixBomberFounders;
    private int enuFighterBase;
    private int enuFighterPremium;
    private int enuFighterFounders;
    private int enuBomberBase;
    private int enuBomberPremium;
    private int enuBomberFounders;
    /** SPELLS */
    private int shockwaveBase;
    private int shockwavePremium;
    private int shockwaveFounders;
    private int plasmaBlastBase;
    private int plasmaBlastPremium;
    private int plasmaBlastFounders;
    private int auroraBeamBase;
    private int auroraBeamPremium;
    private int auroraBeamFounders;
    private int cosmicRainBase;
    private int cosmicRainPremium;
    private int cosmicRainFounders;
    /** SUPPORT */
    private int obixSharpshooterBase;
    private int obixSharpshooterPremium;
    private int obixSharpshooterFounders;
    private int ionInterscoperBase;
    private int ionInterscoperPremium;
    private int ionInterscoperFounders;
    private int gelenatankBase;
    private int gelenatankPremium;
    private int gelenatankFounders;
    private int chemotankBase;
    private int chemotankPremium;
    private int chemotankFounders;
}
